server:
  port: 8082
  contextPath: /files

ai:
  file-manager:
    default-file-root-path: D:\ai
    maximum-thread-count: 10


spring:
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB